.TH "src/rematch/filtering_module/search_variable_set_automaton/dfa Directory Reference" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/filtering_module/search_variable_set_automaton/dfa Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsearch_dfa\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsearch_dfa\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsearch_dfa_state\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsearch_dfa_state\&.hpp\fP"
.br
.in -1c
