.TH "src/rematch/library_interface Directory Reference" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/library_interface Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBflags\&.cpp\fP"
.br
.ti -1c
.RI "file \fBflags\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmatch\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmatch\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmatch_iterator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmatch_iterator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBregex\&.cpp\fP"
.br
.ti -1c
.RI "file \fBregex\&.hpp\fP"
.br
.ti -1c
.RI "file \fBrematch\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrematch\&.hpp\fP"
.br
.in -1c
