.TH "antlr4::ParserErrorListener" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antlr4::ParserErrorListener
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <error_listener\&.hpp>\fP
.PP
Inherits BaseErrorListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsyntaxError\fP (Recognizer *, Token *, size_t line, size_t charPositionInLine, const std::string &msg, std::exception_ptr) override"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void antlr4::ParserErrorListener::syntaxError (Recognizer *, Token *, size_t line, size_t charPositionInLine, const std::string & msg, std::exception_ptr)\fC [inline]\fP, \fC [override]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
