.TH "src/rematch/output_enumeration/ecs_node.hpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/output_enumeration/ecs_node.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cinttypes>\fP
.br
\fC#include <bitset>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrematch::output_enumeration::ECSNode\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrematch\fP"
.br
.ti -1c
.RI "namespace \fBrematch::output_enumeration\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBrematch::output_enumeration::ECSNodeType\fP { \fBrematch::output_enumeration::kBottom\fP = 0, \fBrematch::output_enumeration::kUnion\fP = 1, \fBrematch::output_enumeration::kLabel\fP = 2 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
