.TH "src/rematch/output_enumeration/enumerator.hpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/output_enumeration/enumerator.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'output_enumeration/ecs\&.hpp'\fP
.br
\fC#include 'output_enumeration/mapping\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrematch::output_enumeration::EndOfIterationException\fP"
.br
.ti -1c
.RI "class \fBrematch::output_enumeration::Enumerator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrematch\fP"
.br
.ti -1c
.RI "namespace \fBrematch::output_enumeration\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBrematch::output_enumeration::MAXIMUM_AMOUNT_OF_VARIABLES\fP = 31"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
