.TH "src/rematch/parsing/logical_variable_set_automaton/logical_va_state.cpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/parsing/logical_variable_set_automaton/logical_va_state.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br
\fC#include <set>\fP
.br
\fC#include <bitset>\fP
.br
\fC#include 'parsing/logical_variable_set_automaton/logical_va_state\&.hpp'\fP
.br
\fC#include 'parsing/logical_variable_set_automaton/logical_va_capture\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrematch\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
