.TH "src/rematch/output_enumeration/mapping.hpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/output_enumeration/mapping.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'output_enumeration/ecs\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrematch::output_enumeration::Mapping\fP"
.br
.RI "A \fBMapping\fP is also known as an s-tuple, asigns a span to all it's variables\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrematch\fP"
.br
.ti -1c
.RI "namespace \fBrematch::output_enumeration\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBrematch::output_enumeration::Span\fP = std::pair< int64_t, int64_t >"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
