.TH "src/rematch/library_interface/match.hpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/library_interface/match.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <string_view>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBREMatch::library_interface::Match\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBREMatch\fP"
.br
.ti -1c
.RI "namespace \fBREMatch::library_interface\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBREMatch::library_interface::Span\fP = std::pair< size_t, size_t >"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
