.TH "src/rematch/library_interface/match_iterator.hpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/library_interface/match_iterator.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string_view>\fP
.br
\fC#include 'library_interface/match\&.hpp'\fP
.br
\fC#include 'filtering_module/search_variable_set_automaton/dfa/search_dfa\&.hpp'\fP
.br
\fC#include 'filtering_module/segment_identificator\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBREMatch::library_interface::MatchIterator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBREMatch\fP"
.br
.ti -1c
.RI "namespace \fBREMatch::library_interface\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
