.TH "src/rematch/output_enumeration/minipool.cpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/output_enumeration/minipool.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'output_enumeration/minipool\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrematch\fP"
.br
.ti -1c
.RI "namespace \fBrematch::output_enumeration\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
