.TH "src/rematch/output_enumeration/node_manager.hpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/output_enumeration/node_manager.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'output_enumeration/minipool\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrematch::output_enumeration::NodeManager\fP"
.br
.RI "The Node Manager class stores the pointers to all allocated \fBECSNode\fP's\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrematch\fP"
.br
.ti -1c
.RI "namespace \fBrematch::output_enumeration\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const size_t \fBrematch::output_enumeration::MEMORY_POOL_STARTING_SIZE\fP = 2048"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
