.TH "src/rematch/parsing/parser.hpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/parsing/parser.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string_view>\fP
.br
\fC#include 'parsing/factories/variable_factory\&.hpp'\fP
.br
\fC#include 'parsing/logical_variable_set_automaton/logical_va\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrematch::Parser\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrematch\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
