.TH "src/rematch/library_interface/regex.hpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/library_interface/regex.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <optional>\fP
.br
\fC#include 'library_interface/match\&.hpp'\fP
.br
\fC#include 'library_interface/flags\&.hpp'\fP
.br
\fC#include 'library_interface/match_iterator\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBREMatch::library_interface::Regex\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBREMatch\fP"
.br
.ti -1c
.RI "namespace \fBREMatch::library_interface\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
