.TH "rematch::output_enumeration::MiniPool" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::output_enumeration::MiniPool \- The \fBNodeManager\fP class stores its nodes through a linked list of MiniPools\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <minipool\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMiniPool\fP (size_t cap)"
.br
.ti -1c
.RI "size_t \fBcapacity\fP () const"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "bool \fBis_full\fP () const"
.br
.ti -1c
.RI "\fBMiniPool\fP * \fBnext\fP () const"
.br
.ti -1c
.RI "void \fBset_next\fP (\fBMiniPool\fP *mp)"
.br
.ti -1c
.RI "\fBMiniPool\fP * \fBprev\fP () const"
.br
.ti -1c
.RI "void \fBset_prev\fP (\fBMiniPool\fP *mp)"
.br
.ti -1c
.RI "template<class\&.\&.\&. Args> \fBECSNode\fP * \fBalloc\fP (Args\&.\&.\&. args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBNodeManager\fP class stores its nodes through a linked list of MiniPools\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rematch::output_enumeration::MiniPool::MiniPool (size_t cap)"

.SH "Member Function Documentation"
.PP 
.SS "template<class\&.\&.\&. Args> \fBECSNode\fP * rematch::output_enumeration::MiniPool::alloc (Args\&.\&.\&. args)\fC [inline]\fP"

.SS "size_t rematch::output_enumeration::MiniPool::capacity () const"

.SS "bool rematch::output_enumeration::MiniPool::is_full () const"

.SS "\fBMiniPool\fP * rematch::output_enumeration::MiniPool::next () const"

.SS "\fBMiniPool\fP * rematch::output_enumeration::MiniPool::prev () const"

.SS "void rematch::output_enumeration::MiniPool::set_next (\fBMiniPool\fP * mp)"

.SS "void rematch::output_enumeration::MiniPool::set_prev (\fBMiniPool\fP * mp)"

.SS "size_t rematch::output_enumeration::MiniPool::size () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
