.TH "rematch::SegmentIdentificator" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::SegmentIdentificator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSegmentIdentificator\fP (\fBSearchDFA\fP &search_dfa, std::string_view document)"
.br
.ti -1c
.RI "bool \fBhas_next\fP ()"
.br
.ti -1c
.RI "Span \fBnext\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool rematch::SegmentIdentificator::has_next ()"
Tries to compute the next span that has an output if it is computed correctly, \fBnext()\fP will return that span and the method will return true\&. If not, this method will return false and \fBnext()\fP will return an arbitrary span\&.
.SS "Span rematch::SegmentIdentificator::next ()"
This method returns the current span in the document that has output(s)\&. It MUST be called after \fBhas_next()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
