.TH "REmatchParser::CcEscapesContext" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REmatchParser::CcEscapesContext
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <REmatchParser\&.h>\fP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCcEscapesContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "std::vector< antlr4::tree::TerminalNode * > \fBBACKSLASH\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBBACKSLASH\fP (size_t i)"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBHAT\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBHYPHEN\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBR_BRACK\fP ()"
.br
.ti -1c
.RI "virtual std::any \fBaccept\fP (antlr4::tree::ParseTreeVisitor *visitor) override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "REmatchParser::CcEscapesContext::CcEscapesContext (antlr4::ParserRuleContext * parent, size_t invokingState)"

.SH "Member Function Documentation"
.PP 
.SS "std::any REmatchParser::CcEscapesContext::accept (antlr4::tree::ParseTreeVisitor * visitor)\fC [override]\fP, \fC [virtual]\fP"

.SS "std::vector< tree::TerminalNode * > REmatchParser::CcEscapesContext::BACKSLASH ()"

.SS "tree::TerminalNode * REmatchParser::CcEscapesContext::BACKSLASH (size_t i)"

.SS "size_t REmatchParser::CcEscapesContext::getRuleIndex () const\fC [override]\fP, \fC [virtual]\fP"

.SS "tree::TerminalNode * REmatchParser::CcEscapesContext::HAT ()"

.SS "tree::TerminalNode * REmatchParser::CcEscapesContext::HYPHEN ()"

.SS "tree::TerminalNode * REmatchParser::CcEscapesContext::R_BRACK ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
