.TH "rematch::parsing::CharRange" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::parsing::CharRange
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCharRange\fP (char l, char h)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCharRange\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBlo\fP"
.br
.ti -1c
.RI "char \fBhi\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
