.TH "src/rematch/library_interface/rematch.cpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/library_interface/rematch.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'library_interface/rematch\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBREMatch\fP"
.br
.ti -1c
.RI "namespace \fBREMatch::library_interface\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Regex \fBREMatch::library_interface::compile\fP (std::string_view pattern, Flags flags)"
.br
.ti -1c
.RI "std::optional< Match > \fBREMatch::library_interface::find\fP (std::string_view pattern, std::string_view document, Flags flags)"
.br
.ti -1c
.RI "std::vector< Match > \fBREMatch::library_interface::findall\fP (std::string_view pattern, std::string_view document, Flags flags)"
.br
.ti -1c
.RI "MatchIterator \fBREMatch::library_interface::finditer\fP (std::string_view pattern, std::string_view document, Flags flags)"
.br
.ti -1c
.RI "std::optional< Match > \fBREMatch::library_interface::search\fP (std::string_view pattern, std::string_view document, Flags flags)"
.br
.ti -1c
.RI "std::optional< Match > \fBREMatch::library_interface::match\fP (std::string_view pattern, std::string_view document, Flags flags)"
.br
.ti -1c
.RI "std::optional< Match > \fBREMatch::library_interface::fullmatch\fP (std::string_view pattern, std::string_view document, Flags flags)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
