.TH "rematch::LogicalVACapture" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::LogicalVACapture
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logical_va_capture\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogicalVACapture\fP (\fBLogicalVAState\fP *\fBfrom\fP, std::bitset< 64 > coding, \fBLogicalVAState\fP *\fBnext\fP)"
.br
.ti -1c
.RI "void \fBreset_states\fP (\fBLogicalVAState\fP *insiding, \fBLogicalVAState\fP *to)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBLogicalVACapture\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBLogicalVACapture\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLogicalVAState\fP * \fBfrom\fP"
.br
.ti -1c
.RI "\fBLogicalVAState\fP * \fBnext\fP"
.br
.ti -1c
.RI "std::bitset< 64 > \fBcode\fP"
.br
.ti -1c
.RI "bool \fBflag\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rematch::LogicalVACapture::LogicalVACapture (\fBLogicalVAState\fP * from, std::bitset< 64 > coding, \fBLogicalVAState\fP * next)"

.SH "Member Function Documentation"
.PP 
.SS "bool rematch::LogicalVACapture::operator< (const \fBLogicalVACapture\fP & rhs) const"

.SS "bool rematch::LogicalVACapture::operator== (const \fBLogicalVACapture\fP & rhs) const"

.SS "void rematch::LogicalVACapture::reset_states (\fBLogicalVAState\fP * insiding, \fBLogicalVAState\fP * to)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::bitset<64> rematch::LogicalVACapture::code"

.SS "bool rematch::LogicalVACapture::flag"

.SS "\fBLogicalVAState\fP* rematch::LogicalVACapture::from"

.SS "\fBLogicalVAState\fP* rematch::LogicalVACapture::next"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
