.TH "rematch::visitors" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::visitors
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFilterFactoryVisitor\fP"
.br
.ti -1c
.RI "struct \fBUnicodeRange\fP"
.br
.ti -1c
.RI "struct \fBUnicodeRangeLess\fP"
.br
.ti -1c
.RI "class \fBVariableFactoryVisitor\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBUnicodeRangeSet\fP = std::set< \fBUnicodeRange\fP, \fBUnicodeRangeLess\fP >"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBrematch::visitors::UnicodeRangeSet\fP = typedef std::set<\fBUnicodeRange\fP, \fBUnicodeRangeLess\fP>"

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
