.TH "rematch::parsing::LogicalVAEpsilon" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::parsing::LogicalVAEpsilon
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogicalVAEpsilon\fP (\fBLogicalVAState\fP *from, \fBLogicalVAState\fP *next)"
.br
.ti -1c
.RI "void \fBreset_states\fP (\fBLogicalVAState\fP *s)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLogicalVAState\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBLogicalVAState\fP * \fBfrom\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
