.TH "rematch::CharClass" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::CharClass
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <charclass\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBiterator\fP = CharRangeSet::iterator"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCharClass\fP ()"
.br
.ti -1c
.RI "\fBCharClass\fP (char c)"
.br
.ti -1c
.RI "\fBCharClass\fP (char l, char h)"
.br
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP ()"
.br
.ti -1c
.RI "void \fBadd_charclass\fP (\fBCharClass\fP *cc)"
.br
.ti -1c
.RI "bool \fBadd_range\fP (char l, char h)"
.br
.ti -1c
.RI "bool \fBadd_single\fP (char c)"
.br
.ti -1c
.RI "void \fBnegate\fP ()"
.br
.ti -1c
.RI "\fBCharClass\fP * \fBintersect\fP (\fBCharClass\fP *cc)"
.br
.ti -1c
.RI "\fBCharClass\fP * \fBset_minus\fP (\fBCharClass\fP *cc)"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "bool \fBcontains\fP (char c)"
.br
.ti -1c
.RI "bool \fBis_dot\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCharClass\fP &rhs) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "struct \fBstd::hash< rematch::CharClass >\fP"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, \fBCharClass\fP const &b)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBrematch::CharClass::iterator\fP =  CharRangeSet::iterator"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "rematch::CharClass::CharClass ()"

.SS "rematch::CharClass::CharClass (char c)"

.SS "rematch::CharClass::CharClass (char l, char h)"

.SH "Member Function Documentation"
.PP 
.SS "void rematch::CharClass::add_charclass (\fBCharClass\fP * cc)"

.SS "bool rematch::CharClass::add_range (char l, char h)"

.SS "bool rematch::CharClass::add_single (char c)"

.SS "\fBiterator\fP rematch::CharClass::begin ()\fC [inline]\fP"

.SS "bool rematch::CharClass::contains (char c)"

.SS "bool rematch::CharClass::empty () const\fC [inline]\fP"

.SS "\fBiterator\fP rematch::CharClass::end ()\fC [inline]\fP"

.SS "\fBCharClass\fP * rematch::CharClass::intersect (\fBCharClass\fP * cc)"

.SS "bool rematch::CharClass::is_dot () const\fC [inline]\fP"

.SS "void rematch::CharClass::negate ()"

.SS "bool rematch::CharClass::operator== (const \fBCharClass\fP & rhs) const"

.SS "\fBCharClass\fP * rematch::CharClass::set_minus (\fBCharClass\fP * cc)"

.SS "int rematch::CharClass::size () const\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream & operator<< (std::ostream & os, \fBCharClass\fP const & b)\fC [friend]\fP"

.SS "friend struct std::hash< \fBrematch::CharClass\fP >\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
