.TH "REmatchParserBaseVisitor" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REmatchParserBaseVisitor \- This class provides an empty implementation of \fBREmatchParserVisitor\fP, which can be extended to create a visitor which only needs to handle a subset of the available methods\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <REmatchParserBaseVisitor\&.h>\fP
.PP
Inherits \fBREmatchParserVisitor\fP\&.
.PP
Inherited by \fBrematch::visitors::FilterFactoryVisitor\fP, and \fBrematch::visitors::VariableFactoryVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::any \fBvisitRoot\fP (\fBREmatchParser::RootContext\fP *ctx) override"
.br
.RI "Visit parse trees produced by \fBREmatchParser\fP\&. "
.ti -1c
.RI "virtual std::any \fBvisitAlternation\fP (\fBREmatchParser::AlternationContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitExpr\fP (\fBREmatchParser::ExprContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitElement\fP (\fBREmatchParser::ElementContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitGroup\fP (\fBREmatchParser::GroupContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitParentheses\fP (\fBREmatchParser::ParenthesesContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitAssignation\fP (\fBREmatchParser::AssignationContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitVarname\fP (\fBREmatchParser::VarnameContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitAtom\fP (\fBREmatchParser::AtomContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitCharacterClass\fP (\fBREmatchParser::CharacterClassContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitCcAtom\fP (\fBREmatchParser::CcAtomContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitCcRange\fP (\fBREmatchParser::CcRangeContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitCcSingle\fP (\fBREmatchParser::CcSingleContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitCcLiteral\fP (\fBREmatchParser::CcLiteralContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitCcEscapes\fP (\fBREmatchParser::CcEscapesContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitCcOther\fP (\fBREmatchParser::CcOtherContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitSingleSharedAtom\fP (\fBREmatchParser::SingleSharedAtomContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitLiteral\fP (\fBREmatchParser::LiteralContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitEscapes\fP (\fBREmatchParser::EscapesContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitSpecial\fP (\fBREmatchParser::SpecialContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitOther\fP (\fBREmatchParser::OtherContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitSharedAtom\fP (\fBREmatchParser::SharedAtomContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitQuantifier\fP (\fBREmatchParser::QuantifierContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitQuantity\fP (\fBREmatchParser::QuantityContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitQuantExact\fP (\fBREmatchParser::QuantExactContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitQuantRange\fP (\fBREmatchParser::QuantRangeContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitQuantMin\fP (\fBREmatchParser::QuantMinContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitQuantMax\fP (\fBREmatchParser::QuantMaxContext\fP *ctx) override"
.br
.ti -1c
.RI "virtual std::any \fBvisitNumber\fP (\fBREmatchParser::NumberContext\fP *ctx) override"
.br
.in -1c
.in +1c
.ti -1c
.RI "virtual std::any \fBvisitRoot\fP (\fBREmatchParser::RootContext\fP *context)=0"
.br
.RI "Visit parse trees produced by \fBREmatchParser\fP\&. "
.ti -1c
.RI "virtual std::any \fBvisitAlternation\fP (\fBREmatchParser::AlternationContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitExpr\fP (\fBREmatchParser::ExprContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitElement\fP (\fBREmatchParser::ElementContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitGroup\fP (\fBREmatchParser::GroupContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitParentheses\fP (\fBREmatchParser::ParenthesesContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitAssignation\fP (\fBREmatchParser::AssignationContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitVarname\fP (\fBREmatchParser::VarnameContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitAtom\fP (\fBREmatchParser::AtomContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitCharacterClass\fP (\fBREmatchParser::CharacterClassContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitCcAtom\fP (\fBREmatchParser::CcAtomContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitCcRange\fP (\fBREmatchParser::CcRangeContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitCcSingle\fP (\fBREmatchParser::CcSingleContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitCcLiteral\fP (\fBREmatchParser::CcLiteralContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitCcEscapes\fP (\fBREmatchParser::CcEscapesContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitCcOther\fP (\fBREmatchParser::CcOtherContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitSingleSharedAtom\fP (\fBREmatchParser::SingleSharedAtomContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitLiteral\fP (\fBREmatchParser::LiteralContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitEscapes\fP (\fBREmatchParser::EscapesContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitSpecial\fP (\fBREmatchParser::SpecialContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitOther\fP (\fBREmatchParser::OtherContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitSharedAtom\fP (\fBREmatchParser::SharedAtomContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitQuantifier\fP (\fBREmatchParser::QuantifierContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitQuantity\fP (\fBREmatchParser::QuantityContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitQuantExact\fP (\fBREmatchParser::QuantExactContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitQuantRange\fP (\fBREmatchParser::QuantRangeContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitQuantMin\fP (\fBREmatchParser::QuantMinContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitQuantMax\fP (\fBREmatchParser::QuantMaxContext\fP *context)=0"
.br
.ti -1c
.RI "virtual std::any \fBvisitNumber\fP (\fBREmatchParser::NumberContext\fP *context)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class provides an empty implementation of \fBREmatchParserVisitor\fP, which can be extended to create a visitor which only needs to handle a subset of the available methods\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual std::any REmatchParserBaseVisitor::visitAlternation (\fBREmatchParser::AlternationContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitAssignation (\fBREmatchParser::AssignationContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitAtom (\fBREmatchParser::AtomContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitCcAtom (\fBREmatchParser::CcAtomContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitCcEscapes (\fBREmatchParser::CcEscapesContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitCcLiteral (\fBREmatchParser::CcLiteralContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitCcOther (\fBREmatchParser::CcOtherContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitCcRange (\fBREmatchParser::CcRangeContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitCcSingle (\fBREmatchParser::CcSingleContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitCharacterClass (\fBREmatchParser::CharacterClassContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitElement (\fBREmatchParser::ElementContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitEscapes (\fBREmatchParser::EscapesContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitExpr (\fBREmatchParser::ExprContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitGroup (\fBREmatchParser::GroupContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitLiteral (\fBREmatchParser::LiteralContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitNumber (\fBREmatchParser::NumberContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitOther (\fBREmatchParser::OtherContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitParentheses (\fBREmatchParser::ParenthesesContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitQuantExact (\fBREmatchParser::QuantExactContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitQuantifier (\fBREmatchParser::QuantifierContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitQuantity (\fBREmatchParser::QuantityContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitQuantMax (\fBREmatchParser::QuantMaxContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitQuantMin (\fBREmatchParser::QuantMinContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitQuantRange (\fBREmatchParser::QuantRangeContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitRoot (\fBREmatchParser::RootContext\fP * context)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Visit parse trees produced by \fBREmatchParser\fP\&. 
.PP
Implements \fBREmatchParserVisitor\fP\&.
.PP
Reimplemented in \fBrematch::visitors::VariableFactoryVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitSharedAtom (\fBREmatchParser::SharedAtomContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitSingleSharedAtom (\fBREmatchParser::SingleSharedAtomContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitSpecial (\fBREmatchParser::SpecialContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.
.SS "virtual std::any REmatchParserBaseVisitor::visitVarname (\fBREmatchParser::VarnameContext\fP * ctx)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBREmatchParserVisitor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
