.TH "rematch::output_enumeration::NodeManager" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::output_enumeration::NodeManager \- The Node Manager class stores the pointers to all allocated \fBECSNode\fP's\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <node_manager\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBamount_of_nodes_allocated\fP () const"
.br
.ti -1c
.RI "\fBNodeManager\fP (size_t starting_size=MEMORY_POOL_STARTING_SIZE)"
.br
.ti -1c
.RI "template<class\&.\&.\&. Args> \fBECSNode\fP * \fBalloc\fP (Args &&\&.\&.\&.args)"
.br
.ti -1c
.RI "void \fBdecrease_ref_count\fP (\fBECSNode\fP *node)"
.br
.ti -1c
.RI "void \fBincrease_ref_count\fP (\fBECSNode\fP *node)"
.br
.ti -1c
.RI "void \fBadd_to_list_of_free_memory\fP (\fBECSNode\fP *node)"
.br
.ti -1c
.RI "size_t \fBget_amount_of_nodes_used\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBamount_of_nodes_used\fP {0}"
.br
.ti -1c
.RI "size_t \fBamount_of_recycled_nodes\fP {0}"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Node Manager class stores the pointers to all allocated \fBECSNode\fP's\&. 

When an \fBECSNode\fP is no longer used, i\&.e, when the amount of references to it has become 0, that memory is available to be recycled\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
