.TH "REMatch::library_interface::Regex" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REMatch::library_interface::Regex
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegex\fP (std::string_view pattern, \fBFlags\fP flags=\fBFlags\fP())"
.br
.ti -1c
.RI "std::optional< \fBMatch\fP > \fBfind\fP (std::string_view text, \fBFlags\fP flags=\fBFlags\fP())"
.br
.ti -1c
.RI "\fBMatchIterator\fP \fBfinditer\fP (std::string_view text, \fBFlags\fP flags=\fBFlags\fP())"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
