.TH "rematch::parsing::VariableCatalog" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::parsing::VariableCatalog
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP ()"
.br
.ti -1c
.RI "std::string \fBget_var\fP (uint position)"
.br
.ti -1c
.RI "std::vector< std::string > \fBvariables\fP ()"
.br
.ti -1c
.RI "int \fBposition\fP (std::string var) const"
.br
.ti -1c
.RI "void \fBadd\fP (std::string var)"
.br
.ti -1c
.RI "std::bitset< 64 > \fBopen_code\fP (std::string var)"
.br
.ti -1c
.RI "std::bitset< 64 > \fBclose_code\fP (std::string var)"
.br
.ti -1c
.RI "std::string \fBprint_varset\fP (std::bitset< 64 > code)"
.br
.ti -1c
.RI "std::string \fBpprint\fP ()"
.br
.ti -1c
.RI "void \fBmerge\fP (\fBVariableCatalog\fP &rhs)"
.br
.ti -1c
.RI "bool \fBcontains\fP (std::string var)"
.br
.ti -1c
.RI "bool \fBempty\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBVariableCatalog\fP &vf) const"
.br
.ti -1c
.RI "int & \fBget_offset\fP (int index)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
