.TH "REmatchParser::SingleSharedAtomContext" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REmatchParser::SingleSharedAtomContext
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <REmatchParser\&.h>\fP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleSharedAtomContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "\fBSharedAtomContext\fP * \fBsharedAtom\fP ()"
.br
.ti -1c
.RI "virtual std::any \fBaccept\fP (antlr4::tree::ParseTreeVisitor *visitor) override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "REmatchParser::SingleSharedAtomContext::SingleSharedAtomContext (antlr4::ParserRuleContext * parent, size_t invokingState)"

.SH "Member Function Documentation"
.PP 
.SS "std::any REmatchParser::SingleSharedAtomContext::accept (antlr4::tree::ParseTreeVisitor * visitor)\fC [override]\fP, \fC [virtual]\fP"

.SS "size_t REmatchParser::SingleSharedAtomContext::getRuleIndex () const\fC [override]\fP, \fC [virtual]\fP"

.SS "\fBREmatchParser::SharedAtomContext\fP * REmatchParser::SingleSharedAtomContext::sharedAtom ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
