.TH "REMatch::library_interface::MatchIterator" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REMatch::library_interface::MatchIterator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatchIterator\fP (\fBrematch::SearchDFA\fP &search_dfa, std::string_view &document)"
.br
.ti -1c
.RI "bool \fBhas_next\fP ()"
.br
.ti -1c
.RI "\fBMatch\fP \fBnext\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
