.TH "rematch::SearchNFA" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::SearchNFA
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSearchNFA\fP (\fBLogicalVA\fP const &A)"
.br
.ti -1c
.RI "std::vector< \fBSearchNFAState\fP * > const & \fBget_states\fP () const"
.br
.ti -1c
.RI "\fBSearchNFAState\fP * \fBinitial_state\fP () const"
.br
.ti -1c
.RI "\fBSearchNFAState\fP * \fBaccepting_state\fP () const"
.br
.ti -1c
.RI "void \fBrelabel_states\fP ()"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
