.TH "rematch::CharRangeLess" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::CharRangeLess
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <charclass\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCharRange\fP &a, const \fBCharRange\fP &b) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool rematch::CharRangeLess::operator() (const \fBCharRange\fP & a, const \fBCharRange\fP & b) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
