.TH "rematch::parsing::LogicalVACapture" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::parsing::LogicalVACapture
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogicalVACapture\fP (\fBLogicalVAState\fP *from, std::bitset< 64 > coding, \fBLogicalVAState\fP *next)"
.br
.ti -1c
.RI "void \fBreset_states\fP (\fBLogicalVAState\fP *insiding, \fBLogicalVAState\fP *to)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBLogicalVACapture\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBLogicalVACapture\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLogicalVAState\fP * \fBfrom\fP"
.br
.ti -1c
.RI "\fBLogicalVAState\fP * \fBnext\fP"
.br
.ti -1c
.RI "std::bitset< 64 > \fBcode\fP"
.br
.ti -1c
.RI "bool \fBflag\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool rematch::parsing::LogicalVACapture::operator< (const \fBLogicalVACapture\fP & rhs) const"
Simple ordering for being able to construct an std::set<LogicalVACapture>

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
