.TH "rematch::SearchDFAState" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::SearchDFAState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <search_dfa_state\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFlags\fP { \fBkDefaultSearchNFAState\fP = 0, \fBkAcceptingSearchNFAState\fP = 1, \fBkInitialSearchNFAState\fP = 1 << 1, \fBkEndsNFAState\fP = 1 << 2 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSearchDFAState\fP ()"
.br
.ti -1c
.RI "\fBSearchDFAState\fP (std::set< \fBSearchNFAState\fP * > &states, bool is_ends)"
.br
.ti -1c
.RI "std::vector< \fBSearchNFAState\fP * > \fBsubset\fP () const"
.br
.ti -1c
.RI "std::string \fBlabel\fP () const"
.br
.ti -1c
.RI "int \fBget_id\fP () const"
.br
.ti -1c
.RI "bool \fBempty_subset\fP () const"
.br
.ti -1c
.RI "bool \fBaccepting\fP () const"
.br
.ti -1c
.RI "void \fBset_accepting\fP ()"
.br
.ti -1c
.RI "bool \fBinitial\fP () const"
.br
.ti -1c
.RI "void \fBset_initial\fP ()"
.br
.ti -1c
.RI "bool \fBends\fP () const"
.br
.ti -1c
.RI "void \fBset_ends\fP ()"
.br
.ti -1c
.RI "void \fBadd_direct\fP (char a, \fBSearchDFAState\fP *q)"
.br
.ti -1c
.RI "void \fBadd_capture\fP (char a, std::bitset< 64 > S, \fBSearchDFAState\fP *q)"
.br
.ti -1c
.RI "void \fBadd_empty\fP (char a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBSearchDFAState\fP * > \fBtransitions\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBrematch::SearchDFAState::Flags\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIkDefaultSearchNFAState \fP\fP
.TP
\fB\fIkAcceptingSearchNFAState \fP\fP
.TP
\fB\fIkInitialSearchNFAState \fP\fP
.TP
\fB\fIkEndsNFAState \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rematch::SearchDFAState::SearchDFAState ()"

.SS "rematch::SearchDFAState::SearchDFAState (std::set< \fBSearchNFAState\fP * > & states, bool is_ends)"

.SH "Member Function Documentation"
.PP 
.SS "bool rematch::SearchDFAState::accepting () const\fC [inline]\fP"

.SS "void rematch::SearchDFAState::add_capture (char a, std::bitset< 64 > S, \fBSearchDFAState\fP * q)"

.SS "void rematch::SearchDFAState::add_direct (char a, \fBSearchDFAState\fP * q)"

.SS "void rematch::SearchDFAState::add_empty (char a)"

.SS "bool rematch::SearchDFAState::empty_subset () const\fC [inline]\fP"

.SS "bool rematch::SearchDFAState::ends () const\fC [inline]\fP"

.SS "int rematch::SearchDFAState::get_id () const\fC [inline]\fP"

.SS "bool rematch::SearchDFAState::initial () const\fC [inline]\fP"

.SS "std::string rematch::SearchDFAState::label () const\fC [inline]\fP"

.SS "void rematch::SearchDFAState::set_accepting ()"

.SS "void rematch::SearchDFAState::set_ends ()"

.SS "void rematch::SearchDFAState::set_initial ()"

.SS "std::vector< \fBSearchNFAState\fP * > rematch::SearchDFAState::subset () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBSearchDFAState\fP*> rematch::SearchDFAState::transitions"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
