.TH "rematch::VariableFactory" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::VariableFactory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <variable_factory\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVariableFactory\fP ()"
.br
.ti -1c
.RI "size_t \fBsize\fP ()"
.br
.ti -1c
.RI "std::string \fBget_var\fP (uint \fBposition\fP)"
.br
.ti -1c
.RI "std::vector< std::string > \fBvariables\fP ()"
.br
.ti -1c
.RI "int \fBposition\fP (std::string var) const"
.br
.ti -1c
.RI "void \fBadd\fP (std::string var)"
.br
.ti -1c
.RI "std::bitset< 64 > \fBopen_code\fP (std::string var)"
.br
.ti -1c
.RI "std::bitset< 64 > \fBclose_code\fP (std::string var)"
.br
.ti -1c
.RI "std::string \fBprint_varset\fP (std::bitset< 64 > code)"
.br
.ti -1c
.RI "std::string \fBpprint\fP ()"
.br
.ti -1c
.RI "void \fBmerge\fP (\fBVariableFactory\fP &rhs)"
.br
.ti -1c
.RI "bool \fBcontains\fP (std::string var)"
.br
.ti -1c
.RI "bool \fBempty\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBVariableFactory\fP &vf) const"
.br
.ti -1c
.RI "int & \fBget_offset\fP (int index)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rematch::VariableFactory::VariableFactory ()"

.SH "Member Function Documentation"
.PP 
.SS "void rematch::VariableFactory::add (std::string var)"

.SS "std::bitset< 64 > rematch::VariableFactory::close_code (std::string var)"

.SS "bool rematch::VariableFactory::contains (std::string var)"

.SS "bool rematch::VariableFactory::empty ()"

.SS "int & rematch::VariableFactory::get_offset (int index)\fC [inline]\fP"

.SS "std::string rematch::VariableFactory::get_var (uint position)"

.SS "void rematch::VariableFactory::merge (\fBVariableFactory\fP & rhs)"

.SS "std::bitset< 64 > rematch::VariableFactory::open_code (std::string var)"

.SS "bool rematch::VariableFactory::operator== (const \fBVariableFactory\fP & vf) const"

.SS "int rematch::VariableFactory::position (std::string var) const"

.SS "std::string rematch::VariableFactory::pprint ()"

.SS "std::string rematch::VariableFactory::print_varset (std::bitset< 64 > code)"

.SS "size_t rematch::VariableFactory::size ()\fC [inline]\fP"

.SS "std::vector< std::string > rematch::VariableFactory::variables ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
