.TH "rematch::SearchDFA" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::SearchDFA
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSearchDFA\fP (\fBLogicalVA\fP const &logical_va)"
.br
.ti -1c
.RI "\fBSearchDFAState\fP * \fBget_initial_state\fP ()"
.br
.ti -1c
.RI "std::string \fBpprint\fP ()"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "\fBSearchDFAState\fP * \fBnext_state\fP (char a)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBSearchDFAState\fP * > \fBstates\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBSearchDFAState\fP * rematch::SearchDFA::next_state (char a)"
Assumptions: the ids are from 0 upwards (necessary to use the subsetBitset\&.)

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
