.TH "REMatch::library_interface::Match" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REMatch::library_interface::Match
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatch\fP (Span span, std::string_view document)"
.br
.ti -1c
.RI "Span \fBget_span\fP () const"
.br
.ti -1c
.RI "std::string_view \fBto_string\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
