.TH "rematch::parsing::Parser" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::parsing::Parser
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParser\fP (const std::string_view input)"
.br
.ti -1c
.RI "\fBLogicalVA\fP \fBget_logical_va\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
