.TH "rematch::output_enumeration::Enumerator" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::output_enumeration::Enumerator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnumerator\fP (int amount_of_variables)"
.br
.ti -1c
.RI "void \fBadd_node\fP (\fBECSNode\fP *n)"
.br
.ti -1c
.RI "bool \fBhas_next\fP () const"
.br
.ti -1c
.RI "const \fBMapping\fP * \fBnext\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
