.TH "rematch::LogicalVAFilter" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::LogicalVAFilter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logical_va_filter\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogicalVAFilter\fP (\fBLogicalVAState\fP *\fBfrom\fP, \fBCharClass\fP \fBcharclass\fP, \fBLogicalVAState\fP *\fBnext\fP)"
.br
.ti -1c
.RI "void \fBreset_states\fP (\fBLogicalVAState\fP *s)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBLogicalVAFilter\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLogicalVAState\fP * \fBfrom\fP"
.br
.ti -1c
.RI "\fBLogicalVAState\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBCharClass\fP \fBcharclass\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rematch::LogicalVAFilter::LogicalVAFilter (\fBLogicalVAState\fP * from, \fBCharClass\fP charclass, \fBLogicalVAState\fP * next)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool rematch::LogicalVAFilter::operator== (const \fBLogicalVAFilter\fP & rhs) const\fC [inline]\fP"

.SS "void rematch::LogicalVAFilter::reset_states (\fBLogicalVAState\fP * s)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBCharClass\fP rematch::LogicalVAFilter::charclass"

.SS "\fBLogicalVAState\fP* rematch::LogicalVAFilter::from"

.SS "\fBLogicalVAState\fP* rematch::LogicalVAFilter::next"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
