.TH "rematch::BadRegexException" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::BadRegexException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bad_regex_exception\&.hpp>\fP
.PP
Inherits std::logic_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBadRegexException\fP (std::string error)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const noexcept"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBerror_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rematch::BadRegexException::BadRegexException (std::string error)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual const char * rematch::BadRegexException::what () const\fC [inline]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string rematch::BadRegexException::error_\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
