.TH "rematch::SearchNFAState" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::SearchNFAState
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSearchNFAState\fP (const \fBSearchNFAState\fP &s)"
.br
.ti -1c
.RI "\fBSearchNFAState\fP (const \fBLogicalVAState\fP *state)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "\fBSearchNFAState\fP * \fBnextFilter\fP (\fBCharClass\fP charclass)"
.br
.ti -1c
.RI "void \fBadd_filter\fP (\fBCharClass\fP charclass, \fBSearchNFAState\fP *next)"
.br
.ti -1c
.RI "bool \fBinitial\fP () const"
.br
.ti -1c
.RI "void \fBset_initial\fP (bool b)"
.br
.ti -1c
.RI "bool \fBaccepting\fP () const"
.br
.ti -1c
.RI "void \fBset_accepting\fP (bool b)"
.br
.ti -1c
.RI "bool \fBsuper_final\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSearchNFAState\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBtempMark\fP = false"
.br
.ti -1c
.RI "char \fBcolorMark\fP = 'w'"
.br
.ti -1c
.RI "uint32_t \fBvisitedBy\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.ti -1c
.RI "unsigned int \fBid\fP"
.br
.ti -1c
.RI "std::list< \fBSearchNFAFilter\fP * > \fBfilters\fP"
.br
.ti -1c
.RI "std::list< \fBSearchNFAFilter\fP * > \fBbackward_filters_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
