.TH "REmatchParser::OtherContext" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REmatchParser::OtherContext
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <REmatchParser\&.h>\fP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOtherContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBL_BRACK\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBR_BRACK\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBL_PAR\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBR_PAR\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBL_CURLY\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBR_CURLY\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBSTAR\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBPLUS\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBQUESTION\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBPIPE\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBBACKSLASH\fP ()"
.br
.ti -1c
.RI "virtual std::any \fBaccept\fP (antlr4::tree::ParseTreeVisitor *visitor) override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "REmatchParser::OtherContext::OtherContext (antlr4::ParserRuleContext * parent, size_t invokingState)"

.SH "Member Function Documentation"
.PP 
.SS "std::any REmatchParser::OtherContext::accept (antlr4::tree::ParseTreeVisitor * visitor)\fC [override]\fP, \fC [virtual]\fP"

.SS "tree::TerminalNode * REmatchParser::OtherContext::BACKSLASH ()"

.SS "size_t REmatchParser::OtherContext::getRuleIndex () const\fC [override]\fP, \fC [virtual]\fP"

.SS "tree::TerminalNode * REmatchParser::OtherContext::L_BRACK ()"

.SS "tree::TerminalNode * REmatchParser::OtherContext::L_CURLY ()"

.SS "tree::TerminalNode * REmatchParser::OtherContext::L_PAR ()"

.SS "tree::TerminalNode * REmatchParser::OtherContext::PIPE ()"

.SS "tree::TerminalNode * REmatchParser::OtherContext::PLUS ()"

.SS "tree::TerminalNode * REmatchParser::OtherContext::QUESTION ()"

.SS "tree::TerminalNode * REmatchParser::OtherContext::R_BRACK ()"

.SS "tree::TerminalNode * REmatchParser::OtherContext::R_CURLY ()"

.SS "tree::TerminalNode * REmatchParser::OtherContext::R_PAR ()"

.SS "tree::TerminalNode * REmatchParser::OtherContext::STAR ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
