.TH "REmatchParser::QuantMaxContext" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REmatchParser::QuantMaxContext
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <REmatchParser\&.h>\fP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuantMaxContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBCOMMA\fP ()"
.br
.ti -1c
.RI "\fBNumberContext\fP * \fBnumber\fP ()"
.br
.ti -1c
.RI "virtual std::any \fBaccept\fP (antlr4::tree::ParseTreeVisitor *visitor) override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "REmatchParser::QuantMaxContext::QuantMaxContext (antlr4::ParserRuleContext * parent, size_t invokingState)"

.SH "Member Function Documentation"
.PP 
.SS "std::any REmatchParser::QuantMaxContext::accept (antlr4::tree::ParseTreeVisitor * visitor)\fC [override]\fP, \fC [virtual]\fP"

.SS "tree::TerminalNode * REmatchParser::QuantMaxContext::COMMA ()"

.SS "size_t REmatchParser::QuantMaxContext::getRuleIndex () const\fC [override]\fP, \fC [virtual]\fP"

.SS "\fBREmatchParser::NumberContext\fP * REmatchParser::QuantMaxContext::number ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
