.TH "rematch::output_enumeration::ECSNode" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::output_enumeration::ECSNode
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBECSNode\fP (ECSNodeType node_type, \fBECSNode\fP *left=nullptr, \fBECSNode\fP *right=nullptr, std::bitset< 64 > variable_markers=0, int document_position=0)"
.br
.ti -1c
.RI "\fBECSNode\fP * \fBreset\fP (ECSNodeType node_type, \fBECSNode\fP *left=nullptr, \fBECSNode\fP *right=nullptr, std::bitset< 64 > variable_markers=0, int document_position=0)"
.br
.RI "The reset function reinstantiates the node but recycling the memory position that was used beforehand\&. "
.ti -1c
.RI "bool \fBis_output\fP () const"
.br
.ti -1c
.RI "bool \fBis_bottom\fP () const"
.br
.ti -1c
.RI "\fBECSNode\fP * \fBleft_node\fP () const"
.br
.ti -1c
.RI "\fBECSNode\fP * \fBright_node\fP () const"
.br
.ti -1c
.RI "\fBECSNode\fP * \fBnext\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::bitset< 64 > \fBvariable_markers\fP"
.br
.ti -1c
.RI "\fBECSNode\fP * \fBleft\fP = nullptr"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBECSNode\fP * \fBright\fP = nullptr"
.br
.ti -1c
.RI "   int \fBdocument_position\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "ECSNodeType \fBtype\fP"
.br
.ti -1c
.RI "int \fBref_count\fP {1}"
.br
.ti -1c
.RI "\fBECSNode\fP * \fBnext_free_node\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBNodeManager\fP"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBECSNode\fP &n)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
