.TH "rematch::Parser" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::Parser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parser\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParser\fP (const std::string_view input)"
.br
.ti -1c
.RI "\fBLogicalVA\fP \fBget_logical_va\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rematch::Parser::Parser (const std::string_view input)"

.SH "Member Function Documentation"
.PP 
.SS "\fBLogicalVA\fP rematch::Parser::get_logical_va ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
