.TH "REmatchParser::SpecialContext" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REmatchParser::SpecialContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpecialContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBDOT\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBTAB\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBCARRIAGE_RETURN\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBNEWLINE\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBVERTICAL_WHITESPACE\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBFORM_FEED\fP ()"
.br
.ti -1c
.RI "virtual std::any \fBaccept\fP (antlr4::tree::ParseTreeVisitor *visitor) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
