.TH "rematch::output_enumeration::MiniPool" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::output_enumeration::MiniPool \- The \fBNodeManager\fP class stores its nodes through a linked list of MiniPools\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <minipool\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMiniPool\fP (size_t cap)"
.br
.ti -1c
.RI "size_t \fBcapacity\fP () const"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "bool \fBis_full\fP () const"
.br
.ti -1c
.RI "\fBMiniPool\fP * \fBnext\fP () const"
.br
.ti -1c
.RI "void \fBset_next\fP (\fBMiniPool\fP *mp)"
.br
.ti -1c
.RI "\fBMiniPool\fP * \fBprev\fP () const"
.br
.ti -1c
.RI "void \fBset_prev\fP (\fBMiniPool\fP *mp)"
.br
.ti -1c
.RI "template<class\&.\&.\&. Args> \fBECSNode\fP * \fBalloc\fP (Args\&.\&.\&. args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBNodeManager\fP class stores its nodes through a linked list of MiniPools\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
