.TH "rematch::output_enumeration::ECS" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::output_enumeration::ECS \- An Enumerable Compact Set stores all combinations of outputs through the interface of creating bottom nodes, extend nodes and union nodes such that outputs can be enumerated with constant delay\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ecs\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBget_amount_of_nodes_used\fP () const"
.br
.ti -1c
.RI "size_t \fBamount_of_nodes_allocated\fP () const"
.br
.ti -1c
.RI "\fBECSNode\fP * \fBcreate_bottom_node\fP ()"
.br
.RI "The bottom node, also known as the terminal node, has no children and tells us that we reached the end of an output\&. "
.ti -1c
.RI "\fBECSNode\fP * \fBcreate_extend_node\fP (\fBECSNode\fP *node, std::bitset< 64 > variable_markers, int document_position)"
.br
.RI "Extend nodes, also known as content nodes store the opened and closed variables and the position in the document that this annotation is referring to\&. "
.ti -1c
.RI "\fBECSNode\fP * \fBcreate_union_node\fP (\fBECSNode\fP *node_1, \fBECSNode\fP *node_2)"
.br
.RI "Union nodes allow us to enumerate multiple outputs starting from a single node\&. "
.ti -1c
.RI "\fBECSNode\fP * \fBpin_node\fP (\fBECSNode\fP *node)"
.br
.RI "If the node is going to be used in another scope, it is necessary to pin it so that the memory manager does not recycle its memory location\&. "
.ti -1c
.RI "void \fBunpin_node\fP (\fBECSNode\fP *node)"
.br
.RI "If a node is no longer used, it should be unpinned, this allows the memory manager to recycle the memory allocated to it\&. "
.in -1c
.SH "Detailed Description"
.PP 
An Enumerable Compact Set stores all combinations of outputs through the interface of creating bottom nodes, extend nodes and union nodes such that outputs can be enumerated with constant delay\&. 

Furthermore, memory management is optimized through a node manager, so that memory space is recycled and it is not necessary to allocate memory an extensive amount of times\&.
.PP
This structure is specified by the paper: REmatch: a regex engine for finding all matches (Riveros, Van Sint, Vrgoc 2023)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
