.TH "rematch::parsing::BadRegexException" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::parsing::BadRegexException
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::logic_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBadRegexException\fP (std::string error)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const noexcept"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBerror_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
