.TH "REmatchParser::ParenthesesContext" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REmatchParser::ParenthesesContext
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <REmatchParser\&.h>\fP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParenthesesContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBL_PAR\fP ()"
.br
.ti -1c
.RI "\fBAlternationContext\fP * \fBalternation\fP ()"
.br
.ti -1c
.RI "antlr4::tree::TerminalNode * \fBR_PAR\fP ()"
.br
.ti -1c
.RI "virtual std::any \fBaccept\fP (antlr4::tree::ParseTreeVisitor *visitor) override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "REmatchParser::ParenthesesContext::ParenthesesContext (antlr4::ParserRuleContext * parent, size_t invokingState)"

.SH "Member Function Documentation"
.PP 
.SS "std::any REmatchParser::ParenthesesContext::accept (antlr4::tree::ParseTreeVisitor * visitor)\fC [override]\fP, \fC [virtual]\fP"

.SS "\fBREmatchParser::AlternationContext\fP * REmatchParser::ParenthesesContext::alternation ()"

.SS "size_t REmatchParser::ParenthesesContext::getRuleIndex () const\fC [override]\fP, \fC [virtual]\fP"

.SS "tree::TerminalNode * REmatchParser::ParenthesesContext::L_PAR ()"

.SS "tree::TerminalNode * REmatchParser::ParenthesesContext::R_PAR ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
