.TH "REMatch::library_interface::MatchIterator" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REMatch::library_interface::MatchIterator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <match_iterator\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatchIterator\fP (\fBrematch::SearchDFA\fP &search_dfa, std::string_view &document)"
.br
.ti -1c
.RI "bool \fBhas_next\fP ()"
.br
.ti -1c
.RI "\fBMatch\fP \fBnext\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "REMatch::library_interface::MatchIterator::MatchIterator (\fBrematch::SearchDFA\fP & search_dfa, std::string_view & document)"

.SH "Member Function Documentation"
.PP 
.SS "bool REMatch::library_interface::MatchIterator::has_next ()"

.SS "\fBMatch\fP REMatch::library_interface::MatchIterator::next ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
