.TH "REMatch::library_interface::Match" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REMatch::library_interface::Match
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <match\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatch\fP (\fBSpan\fP span, std::string_view document)"
.br
.ti -1c
.RI "\fBSpan\fP \fBget_span\fP () const"
.br
.ti -1c
.RI "std::string_view \fBto_string\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "REMatch::library_interface::Match::Match (\fBSpan\fP span, std::string_view document)"

.SH "Member Function Documentation"
.PP 
.SS "\fBSpan\fP REMatch::library_interface::Match::get_span () const"

.SS "std::string_view REMatch::library_interface::Match::to_string () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
