.TH "rematch::output_enumeration" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::output_enumeration
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBECS\fP"
.br
.RI "An Enumerable Compact Set stores all combinations of outputs through the interface of creating bottom nodes, extend nodes and union nodes such that outputs can be enumerated with constant delay\&. "
.ti -1c
.RI "class \fBECSNode\fP"
.br
.ti -1c
.RI "class \fBEndOfIterationException\fP"
.br
.ti -1c
.RI "class \fBEnumerator\fP"
.br
.ti -1c
.RI "class \fBMapping\fP"
.br
.RI "A \fBMapping\fP is also known as an s-tuple, asigns a span to all it's variables\&. "
.ti -1c
.RI "class \fBMiniPool\fP"
.br
.RI "The \fBNodeManager\fP class stores its nodes through a linked list of MiniPools\&. "
.ti -1c
.RI "class \fBNodeManager\fP"
.br
.RI "The Node Manager class stores the pointers to all allocated \fBECSNode\fP's\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBSpan\fP = std::pair< int64_t, int64_t >"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBECSNodeType\fP { \fBkBottom\fP = 0, \fBkUnion\fP = 1, \fBkLabel\fP = 2 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBECSNode\fP &n)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBMAXIMUM_AMOUNT_OF_VARIABLES\fP = 31"
.br
.ti -1c
.RI "const size_t \fBMEMORY_POOL_STARTING_SIZE\fP = 2048"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBrematch::output_enumeration::Span\fP = typedef std::pair<int64_t, int64_t>"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBrematch::output_enumeration::ECSNodeType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIkBottom \fP\fP
.TP
\fB\fIkUnion \fP\fP
.TP
\fB\fIkLabel \fP\fP
.SH "Function Documentation"
.PP 
.SS "std::ostream & rematch::output_enumeration::operator<< (std::ostream & os, const \fBECSNode\fP & n)"

.SH "Variable Documentation"
.PP 
.SS "const int rematch::output_enumeration::MAXIMUM_AMOUNT_OF_VARIABLES = 31"

.SS "const size_t rematch::output_enumeration::MEMORY_POOL_STARTING_SIZE = 2048"

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
