.TH "rematch::visitors::UnicodeRange" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::visitors::UnicodeRange
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <filter_factory_visitor\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnicodeRange\fP ()"
.br
.ti -1c
.RI "\fBUnicodeRange\fP (uint32_t l, uint32_t h)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBUnicodeRange\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBlo\fP"
.br
.ti -1c
.RI "uint32_t \fBhi\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rematch::visitors::UnicodeRange::UnicodeRange ()\fC [inline]\fP"

.SS "rematch::visitors::UnicodeRange::UnicodeRange (uint32_t l, uint32_t h)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool rematch::visitors::UnicodeRange::operator== (const \fBUnicodeRange\fP & rhs) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "uint32_t rematch::visitors::UnicodeRange::hi"

.SS "uint32_t rematch::visitors::UnicodeRange::lo"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
