.TH "REmatchParser::ElementContext" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REmatchParser::ElementContext
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <REmatchParser\&.h>\fP
.PP
Inherits antlr4::ParserRuleContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElementContext\fP (antlr4::ParserRuleContext *parent, size_t invokingState)"
.br
.ti -1c
.RI "virtual size_t \fBgetRuleIndex\fP () const override"
.br
.ti -1c
.RI "\fBGroupContext\fP * \fBgroup\fP ()"
.br
.ti -1c
.RI "\fBQuantifierContext\fP * \fBquantifier\fP ()"
.br
.ti -1c
.RI "virtual std::any \fBaccept\fP (antlr4::tree::ParseTreeVisitor *visitor) override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "REmatchParser::ElementContext::ElementContext (antlr4::ParserRuleContext * parent, size_t invokingState)"

.SH "Member Function Documentation"
.PP 
.SS "std::any REmatchParser::ElementContext::accept (antlr4::tree::ParseTreeVisitor * visitor)\fC [override]\fP, \fC [virtual]\fP"

.SS "size_t REmatchParser::ElementContext::getRuleIndex () const\fC [override]\fP, \fC [virtual]\fP"

.SS "\fBREmatchParser::GroupContext\fP * REmatchParser::ElementContext::group ()"

.SS "\fBREmatchParser::QuantifierContext\fP * REmatchParser::ElementContext::quantifier ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
