.TH "rematch::visitors::UnicodeRange" 3 "Tue Jan 31 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::visitors::UnicodeRange
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnicodeRange\fP (uint32_t l, uint32_t h)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBUnicodeRange\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBlo\fP"
.br
.ti -1c
.RI "uint32_t \fBhi\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
