.TH "rematch::CharRange" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::CharRange
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <charclass\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCharRange\fP ()"
.br
.ti -1c
.RI "\fBCharRange\fP (char l, char h)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCharRange\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBlo\fP"
.br
.ti -1c
.RI "char \fBhi\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rematch::CharRange::CharRange ()\fC [inline]\fP"

.SS "rematch::CharRange::CharRange (char l, char h)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool rematch::CharRange::operator== (const \fBCharRange\fP & rhs) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "char rematch::CharRange::hi"

.SS "char rematch::CharRange::lo"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
