.TH "REmatchParser" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REmatchParser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <REmatchParser\&.h>\fP
.PP
Inherits antlr4::Parser\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlternationContext\fP"
.br
.ti -1c
.RI "class \fBAssignationContext\fP"
.br
.ti -1c
.RI "class \fBAtomContext\fP"
.br
.ti -1c
.RI "class \fBCcAtomContext\fP"
.br
.ti -1c
.RI "class \fBCcEscapesContext\fP"
.br
.ti -1c
.RI "class \fBCcLiteralContext\fP"
.br
.ti -1c
.RI "class \fBCcOtherContext\fP"
.br
.ti -1c
.RI "class \fBCcRangeContext\fP"
.br
.ti -1c
.RI "class \fBCcSingleContext\fP"
.br
.ti -1c
.RI "class \fBCharacterClassContext\fP"
.br
.ti -1c
.RI "class \fBElementContext\fP"
.br
.ti -1c
.RI "class \fBEscapesContext\fP"
.br
.ti -1c
.RI "class \fBExprContext\fP"
.br
.ti -1c
.RI "class \fBGroupContext\fP"
.br
.ti -1c
.RI "class \fBLiteralContext\fP"
.br
.ti -1c
.RI "class \fBNumberContext\fP"
.br
.ti -1c
.RI "class \fBOtherContext\fP"
.br
.ti -1c
.RI "class \fBParenthesesContext\fP"
.br
.ti -1c
.RI "class \fBQuantExactContext\fP"
.br
.ti -1c
.RI "class \fBQuantifierContext\fP"
.br
.ti -1c
.RI "class \fBQuantityContext\fP"
.br
.ti -1c
.RI "class \fBQuantMaxContext\fP"
.br
.ti -1c
.RI "class \fBQuantMinContext\fP"
.br
.ti -1c
.RI "class \fBQuantRangeContext\fP"
.br
.ti -1c
.RI "class \fBRootContext\fP"
.br
.ti -1c
.RI "class \fBSharedAtomContext\fP"
.br
.ti -1c
.RI "class \fBSingleSharedAtomContext\fP"
.br
.ti -1c
.RI "class \fBSpecialContext\fP"
.br
.ti -1c
.RI "class \fBVarnameContext\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBDECIMAL_DIGIT\fP = 1, \fBNOT_DECIMAL_DIGIT\fP = 2, \fBWHITESPACE\fP = 3, \fBNOT_WHITESPACE\fP = 4, \fBALPHANUMERIC\fP = 5, \fBNOT_ALPHANUMERIC\fP = 6, \fBTAB\fP = 7, \fBCARRIAGE_RETURN\fP = 8, \fBNEWLINE\fP = 9, \fBVERTICAL_WHITESPACE\fP = 10, \fBFORM_FEED\fP = 11, \fBPIPE\fP = 12, \fBEXCLAMAITON\fP = 13, \fBL_CURLY\fP = 14, \fBR_CURLY\fP = 15, \fBL_PAR\fP = 16, \fBR_PAR\fP = 17, \fBCOMMA\fP = 18, \fBQUESTION\fP = 19, \fBPLUS\fP = 20, \fBSTAR\fP = 21, \fBHAT\fP = 22, \fBHYPHEN\fP = 23, \fBL_BRACK\fP = 24, \fBR_BRACK\fP = 25, \fBBACKSLASH\fP = 26, \fBALPHA\fP = 27, \fBDIGIT\fP = 28, \fBDOT\fP = 29, \fBUNRECOGNIZED\fP = 30 }"
.br
.ti -1c
.RI "enum { \fBRuleRoot\fP = 0, \fBRuleAlternation\fP = 1, \fBRuleExpr\fP = 2, \fBRuleElement\fP = 3, \fBRuleGroup\fP = 4, \fBRuleParentheses\fP = 5, \fBRuleAssignation\fP = 6, \fBRuleVarname\fP = 7, \fBRuleAtom\fP = 8, \fBRuleCharacterClass\fP = 9, \fBRuleCcAtom\fP = 10, \fBRuleCcRange\fP = 11, \fBRuleCcSingle\fP = 12, \fBRuleCcLiteral\fP = 13, \fBRuleCcEscapes\fP = 14, \fBRuleCcOther\fP = 15, \fBRuleSingleSharedAtom\fP = 16, \fBRuleLiteral\fP = 17, \fBRuleEscapes\fP = 18, \fBRuleSpecial\fP = 19, \fBRuleOther\fP = 20, \fBRuleSharedAtom\fP = 21, \fBRuleQuantifier\fP = 22, \fBRuleQuantity\fP = 23, \fBRuleQuantExact\fP = 24, \fBRuleQuantRange\fP = 25, \fBRuleQuantMin\fP = 26, \fBRuleQuantMax\fP = 27, \fBRuleNumber\fP = 28 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBREmatchParser\fP (antlr4::TokenStream *input)"
.br
.ti -1c
.RI "\fBREmatchParser\fP (antlr4::TokenStream *input, const antlr4::atn::ParserATNSimulatorOptions &options)"
.br
.ti -1c
.RI "\fB~REmatchParser\fP () override"
.br
.ti -1c
.RI "std::string \fBgetGrammarFileName\fP () const override"
.br
.ti -1c
.RI "const antlr4::atn::ATN & \fBgetATN\fP () const override"
.br
.ti -1c
.RI "const std::vector< std::string > & \fBgetRuleNames\fP () const override"
.br
.ti -1c
.RI "const antlr4::dfa::Vocabulary & \fBgetVocabulary\fP () const override"
.br
.ti -1c
.RI "antlr4::atn::SerializedATNView \fBgetSerializedATN\fP () const override"
.br
.ti -1c
.RI "\fBRootContext\fP * \fBroot\fP ()"
.br
.ti -1c
.RI "\fBAlternationContext\fP * \fBalternation\fP ()"
.br
.ti -1c
.RI "\fBExprContext\fP * \fBexpr\fP ()"
.br
.ti -1c
.RI "\fBElementContext\fP * \fBelement\fP ()"
.br
.ti -1c
.RI "\fBGroupContext\fP * \fBgroup\fP ()"
.br
.ti -1c
.RI "\fBParenthesesContext\fP * \fBparentheses\fP ()"
.br
.ti -1c
.RI "\fBAssignationContext\fP * \fBassignation\fP ()"
.br
.ti -1c
.RI "\fBVarnameContext\fP * \fBvarname\fP ()"
.br
.ti -1c
.RI "\fBAtomContext\fP * \fBatom\fP ()"
.br
.ti -1c
.RI "\fBCharacterClassContext\fP * \fBcharacterClass\fP ()"
.br
.ti -1c
.RI "\fBCcAtomContext\fP * \fBccAtom\fP ()"
.br
.ti -1c
.RI "\fBCcRangeContext\fP * \fBccRange\fP ()"
.br
.ti -1c
.RI "\fBCcSingleContext\fP * \fBccSingle\fP ()"
.br
.ti -1c
.RI "\fBCcLiteralContext\fP * \fBccLiteral\fP ()"
.br
.ti -1c
.RI "\fBCcEscapesContext\fP * \fBccEscapes\fP ()"
.br
.ti -1c
.RI "\fBCcOtherContext\fP * \fBccOther\fP ()"
.br
.ti -1c
.RI "\fBSingleSharedAtomContext\fP * \fBsingleSharedAtom\fP ()"
.br
.ti -1c
.RI "\fBLiteralContext\fP * \fBliteral\fP ()"
.br
.ti -1c
.RI "\fBEscapesContext\fP * \fBescapes\fP ()"
.br
.ti -1c
.RI "\fBSpecialContext\fP * \fBspecial\fP ()"
.br
.ti -1c
.RI "\fBOtherContext\fP * \fBother\fP ()"
.br
.ti -1c
.RI "\fBSharedAtomContext\fP * \fBsharedAtom\fP ()"
.br
.ti -1c
.RI "\fBQuantifierContext\fP * \fBquantifier\fP ()"
.br
.ti -1c
.RI "\fBQuantityContext\fP * \fBquantity\fP ()"
.br
.ti -1c
.RI "\fBQuantExactContext\fP * \fBquantExact\fP ()"
.br
.ti -1c
.RI "\fBQuantRangeContext\fP * \fBquantRange\fP ()"
.br
.ti -1c
.RI "\fBQuantMinContext\fP * \fBquantMin\fP ()"
.br
.ti -1c
.RI "\fBQuantMaxContext\fP * \fBquantMax\fP ()"
.br
.ti -1c
.RI "\fBNumberContext\fP * \fBnumber\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinitialize\fP ()"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDECIMAL_DIGIT \fP\fP
.TP
\fB\fINOT_DECIMAL_DIGIT \fP\fP
.TP
\fB\fIWHITESPACE \fP\fP
.TP
\fB\fINOT_WHITESPACE \fP\fP
.TP
\fB\fIALPHANUMERIC \fP\fP
.TP
\fB\fINOT_ALPHANUMERIC \fP\fP
.TP
\fB\fITAB \fP\fP
.TP
\fB\fICARRIAGE_RETURN \fP\fP
.TP
\fB\fINEWLINE \fP\fP
.TP
\fB\fIVERTICAL_WHITESPACE \fP\fP
.TP
\fB\fIFORM_FEED \fP\fP
.TP
\fB\fIPIPE \fP\fP
.TP
\fB\fIEXCLAMAITON \fP\fP
.TP
\fB\fIL_CURLY \fP\fP
.TP
\fB\fIR_CURLY \fP\fP
.TP
\fB\fIL_PAR \fP\fP
.TP
\fB\fIR_PAR \fP\fP
.TP
\fB\fICOMMA \fP\fP
.TP
\fB\fIQUESTION \fP\fP
.TP
\fB\fIPLUS \fP\fP
.TP
\fB\fISTAR \fP\fP
.TP
\fB\fIHAT \fP\fP
.TP
\fB\fIHYPHEN \fP\fP
.TP
\fB\fIL_BRACK \fP\fP
.TP
\fB\fIR_BRACK \fP\fP
.TP
\fB\fIBACKSLASH \fP\fP
.TP
\fB\fIALPHA \fP\fP
.TP
\fB\fIDIGIT \fP\fP
.TP
\fB\fIDOT \fP\fP
.TP
\fB\fIUNRECOGNIZED \fP\fP
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRuleRoot \fP\fP
.TP
\fB\fIRuleAlternation \fP\fP
.TP
\fB\fIRuleExpr \fP\fP
.TP
\fB\fIRuleElement \fP\fP
.TP
\fB\fIRuleGroup \fP\fP
.TP
\fB\fIRuleParentheses \fP\fP
.TP
\fB\fIRuleAssignation \fP\fP
.TP
\fB\fIRuleVarname \fP\fP
.TP
\fB\fIRuleAtom \fP\fP
.TP
\fB\fIRuleCharacterClass \fP\fP
.TP
\fB\fIRuleCcAtom \fP\fP
.TP
\fB\fIRuleCcRange \fP\fP
.TP
\fB\fIRuleCcSingle \fP\fP
.TP
\fB\fIRuleCcLiteral \fP\fP
.TP
\fB\fIRuleCcEscapes \fP\fP
.TP
\fB\fIRuleCcOther \fP\fP
.TP
\fB\fIRuleSingleSharedAtom \fP\fP
.TP
\fB\fIRuleLiteral \fP\fP
.TP
\fB\fIRuleEscapes \fP\fP
.TP
\fB\fIRuleSpecial \fP\fP
.TP
\fB\fIRuleOther \fP\fP
.TP
\fB\fIRuleSharedAtom \fP\fP
.TP
\fB\fIRuleQuantifier \fP\fP
.TP
\fB\fIRuleQuantity \fP\fP
.TP
\fB\fIRuleQuantExact \fP\fP
.TP
\fB\fIRuleQuantRange \fP\fP
.TP
\fB\fIRuleQuantMin \fP\fP
.TP
\fB\fIRuleQuantMax \fP\fP
.TP
\fB\fIRuleNumber \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "REmatchParser::REmatchParser (antlr4::TokenStream * input)\fC [explicit]\fP"

.SS "REmatchParser::REmatchParser (antlr4::TokenStream * input, const antlr4::atn::ParserATNSimulatorOptions & options)"

.SS "REmatchParser::~REmatchParser ()\fC [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBREmatchParser::AlternationContext\fP * REmatchParser::alternation ()"

.SS "\fBREmatchParser::AssignationContext\fP * REmatchParser::assignation ()"

.SS "\fBREmatchParser::AtomContext\fP * REmatchParser::atom ()"

.SS "\fBREmatchParser::CcAtomContext\fP * REmatchParser::ccAtom ()"

.SS "\fBREmatchParser::CcEscapesContext\fP * REmatchParser::ccEscapes ()"

.SS "\fBREmatchParser::CcLiteralContext\fP * REmatchParser::ccLiteral ()"

.SS "\fBREmatchParser::CcOtherContext\fP * REmatchParser::ccOther ()"

.SS "\fBREmatchParser::CcRangeContext\fP * REmatchParser::ccRange ()"

.SS "\fBREmatchParser::CcSingleContext\fP * REmatchParser::ccSingle ()"

.SS "\fBREmatchParser::CharacterClassContext\fP * REmatchParser::characterClass ()"

.SS "\fBREmatchParser::ElementContext\fP * REmatchParser::element ()"

.SS "\fBREmatchParser::EscapesContext\fP * REmatchParser::escapes ()"

.SS "\fBREmatchParser::ExprContext\fP * REmatchParser::expr ()"

.SS "const atn::ATN & REmatchParser::getATN () const\fC [override]\fP"

.SS "std::string REmatchParser::getGrammarFileName () const\fC [override]\fP"

.SS "const std::vector< std::string > & REmatchParser::getRuleNames () const\fC [override]\fP"

.SS "antlr4::atn::SerializedATNView REmatchParser::getSerializedATN () const\fC [override]\fP"

.SS "const dfa::Vocabulary & REmatchParser::getVocabulary () const\fC [override]\fP"

.SS "\fBREmatchParser::GroupContext\fP * REmatchParser::group ()"

.SS "void REmatchParser::initialize ()\fC [static]\fP"

.SS "\fBREmatchParser::LiteralContext\fP * REmatchParser::literal ()"

.SS "\fBREmatchParser::NumberContext\fP * REmatchParser::number ()"

.SS "\fBREmatchParser::OtherContext\fP * REmatchParser::other ()"

.SS "\fBREmatchParser::ParenthesesContext\fP * REmatchParser::parentheses ()"

.SS "\fBREmatchParser::QuantExactContext\fP * REmatchParser::quantExact ()"

.SS "\fBREmatchParser::QuantifierContext\fP * REmatchParser::quantifier ()"

.SS "\fBREmatchParser::QuantityContext\fP * REmatchParser::quantity ()"

.SS "\fBREmatchParser::QuantMaxContext\fP * REmatchParser::quantMax ()"

.SS "\fBREmatchParser::QuantMinContext\fP * REmatchParser::quantMin ()"

.SS "\fBREmatchParser::QuantRangeContext\fP * REmatchParser::quantRange ()"

.SS "\fBREmatchParser::RootContext\fP * REmatchParser::root ()"

.SS "\fBREmatchParser::SharedAtomContext\fP * REmatchParser::sharedAtom ()"

.SS "\fBREmatchParser::SingleSharedAtomContext\fP * REmatchParser::singleSharedAtom ()"

.SS "\fBREmatchParser::SpecialContext\fP * REmatchParser::special ()"

.SS "\fBREmatchParser::VarnameContext\fP * REmatchParser::varname ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
