.TH "rematch::LogicalVAEpsilon" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rematch::LogicalVAEpsilon
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logical_va_epsilon\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogicalVAEpsilon\fP (\fBLogicalVAState\fP *\fBfrom\fP, \fBLogicalVAState\fP *\fBnext\fP)"
.br
.ti -1c
.RI "void \fBreset_states\fP (\fBLogicalVAState\fP *s)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLogicalVAState\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBLogicalVAState\fP * \fBfrom\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rematch::LogicalVAEpsilon::LogicalVAEpsilon (\fBLogicalVAState\fP * from, \fBLogicalVAState\fP * next)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void rematch::LogicalVAEpsilon::reset_states (\fBLogicalVAState\fP * s)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBLogicalVAState\fP* rematch::LogicalVAEpsilon::from"

.SS "\fBLogicalVAState\fP* rematch::LogicalVAEpsilon::next"


.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
