.TH "src/rematch/filtering_module/search_variable_set_automaton/nfa/search_nfa.cpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/filtering_module/search_variable_set_automaton/nfa/search_nfa.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'filtering_module/search_variable_set_automaton/nfa/search_nfa\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'parsing/charclass\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrematch\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
