.TH "src/rematch/filtering_module/search_variable_set_automaton/nfa/search_nfa_state.hpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/filtering_module/search_variable_set_automaton/nfa/search_nfa_state.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br
\fC#include <set>\fP
.br
\fC#include <bitset>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'parsing/charclass\&.hpp'\fP
.br
\fC#include 'parsing/logical_variable_set_automaton/logical_va_state\&.hpp'\fP
.br
\fC#include 'filtering_module/search_variable_set_automaton/nfa/search_nfa_filter\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrematch::SearchNFAState\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrematch\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBrematch::SearchNFAStateFlags\fP { \fBrematch::kDefaultSearchNFAState\fP = 0, \fBrematch::kFinalSearchNFAState\fP = 1, \fBrematch::kSuperFinalSearchNFAState\fP = 1 << 1, \fBrematch::kInitialSearchNFAState\fP = 1 << 2 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
