.TH "src/rematch/filtering_module/segment_identificator.cpp" 3 "Mon Jan 30 2023" "Version 1" "Rematch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rematch/filtering_module/segment_identificator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'filtering_module/segment_identificator\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrematch\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFORCE_INLINE\fP   inline __attribute__((always_inline))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FORCE_INLINE   inline __attribute__((always_inline))"

.SH "Author"
.PP 
Generated automatically by Doxygen for Rematch from the source code\&.
