name: Wheel builder
on:
  workflow_dispatch:

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build sdist
        run: |
          python -m pip install -U pip build
          python -m build --sdist
  
      - name: Test the sdist
        run: |
          python -m pip install dist/*.gz
          cd .. # Can't import pyrematch within pyrematch's src directory
          python -c "import pyrematch, sys; print(pyrematch.Regex); sys.exit(0)" # TODO: Change this to pyrematch.__version__


  build_wheels:
    if: false
    name: Build wheel for ${{ matrix.python }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      matrix:
        # Github Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
          - [ubuntu-20.04, manylinux_x86_64]
          # - [ubuntu-20.04, musllinux_x86_64]
          # - [macos-12, macosx_x86_64]
          # - [windows-2019, win_amd64]
          # - [windows-2019, win32]
        python: ["cp39"] #, "cp310", "cp311", "cp312", ]
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python }}-${{ startsWith(matrix.buildplat[1], 'macosx') && 'macosx' || matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl
