name: Wheel builder
on:
  workflow_dispatch:

jobs:
  build_sdist:
    if: false
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build sdist
        run: |
          python -m pip install -U pip build
          python -m build --sdist
  
      - name: Test the sdist
        run: |
          python -m pip install dist/*.gz
          cd .. # Can't import pyrematch within pyrematch's src directory
          python -c "import pyrematch, sys; print(pyrematch.Regex); sys.exit(0)" # TODO: Change this to pyrematch.__version__


  build_wheels:
    name: Build wheel for ${{ matrix.python }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      # All wheels must be built in order to complete this job
      matrix:
        buildplat:
          - [macos-latest, macosx_arm64]
          # - [ubuntu-20.04, manylinux_x86_64]
          # - [macos-latest, macosx_x86_64]
          # - [windows-2019, win32]
          # - [ubuntu-20.04, musllinux_x86_64]
          # - [windows-2019, win_amd64]
        python: ["cp39"] # ["cp38", "cp39", "cp310", "cp311", "cp312"]
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          # In order to have full C++17 support
          CIBW_ENVIRONMENT_MACOS: >
            MACOSX_DEPLOYMENT_TARGET='10.14'
